[build]
  command = "npm run vercel-build"
  publish = "dist/public"

[[redirects]]
  from = "/api/*"
  to = "https://your-backend-url.vercel.app/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/ws"
  to = "https://your-backend-url.vercel.app/ws"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
